spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_board
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: Asia/Seoul